#- name: demo on loops
#  hosts: localhost
#  tasks:
#    - name: loops demo
#      ansible.builtin.debug:
#        msg: "Fruit name - {{item}}"
#      loop:
#        - apple
#        - orange
- name: demo on loops in list of maps
  hosts: localhost
  tasks:
    - name: loops demo in lists
      ansible.builtin.debug:
        msg: "Fruit name - {{item.name}} , count - {{item.count}}"
      loop:
        - {name: "apple", count:100}
        - {name: "orange", count:500}
