#- name: print parameter
#  hosts: localhost
#  tasks:
#    - name: print a parameter
#      ansible.builtin.debug:
#        msg: "{{ lookup('aws_ssm', 'params.dev.catalogue', region='us-east-1' ) }}"

- name: create new parameter in parameter store
  hosts: localhost
  tasks:
    - name: create parameter
      community.aws.ssm_parameter:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: "us-east-1"
      loop:
        - {name: params.dev.catalogue.MONGO, value: 'true' }
        - {name: params.dev.catalogue.MONGO_URL, value: 'mongodb://172.31.88.195:27017/catalogue' }
