#- name: print parameter
#  hosts: localhost
#  tasks:
#    - name: print a parameter
#      ansible.builtin.debug:
#        msg: "{{ lookup('aws_ssm', 'params.dev.catalogue', region='us-east-1' ) }}"

- name: create new parameter in parameter store
  hosts: localhost
  tasks:
    - name: create parameter
      community.aws.ssm_parameter:
        name: "params.dev.mongo"
        value: "100"
        region: "us-east-1"
