- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: copy roboshop configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Enable nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
