- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Add application user
  when: APP_USER is defined
  ansible.builtin.user:
    name: "{{ APP_USER }}"


#  if [ ! -z "$APP_USER" ]; then
#  PRINT "Adding application user"
#  id roboshop &>>$LOG
#  if [ $? -ne 0 ]; then
#  useradd roboshop &>>$LOG
#  fi
#  STAT $?
#  fi
#  PRINT "download app content"
#  curl -s -L -o /tmp/${COMPONENT}.zip "https://github.com/roboshop-devops-project/${COMPONENT}/archive/main.zip" &>>$LOG
#  STAT $?
#
#  PRINT "remove previous "
#  cd $APP_LOC &>>$LOG
#  rm -rf ${CONTENT} &>>$LOG
#  STAT $?
#
#  PRINT "extracting app content"
#  unzip -o /tmp/${COMPONENT}.zip &>>$LOG
#  STAT $?
#  COMPONENT=frontend
#  source common.sh

#
#  APP_LOC=/usr/share/nginx/html
#
#  DOWNLOAD_APP_CODE
#
#  mv frontend-main/static/* . &>>{LOG}
#  mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf &>>{LOG}
#
#  PRINT "Update RoboShop Configuration"
#  sed -i -e '/catalogue/ s/localhost/dev-catalogue.mydevops410.online/' -e '/user/ s/localhost/dev-user.mydevops410.online/' -e '/cart/ s/localhost/dev-cart.mydevops410.online/' -e '/shipping/ s/localhost/dev-shipping.mydevops410.online/' -e '/payment/ s/localhost/dev-payment.mydevops410.online/' /etc/nginx/default.d/roboshop.conf
#  STAT $?
#
#  PRINT "enable nginx"
#  systemctl enable nginx &>>{LOG}
#  STAT $?
#
#  PRINT "restart nginx"
#  systemctl restart nginx &>>{LOG}
#  STAT $?
#- name: start nginx
#  ansible.builtin.service:
#    name: nginx
#    state: started
#    enabled: yes
#
#- name: download nginx docs
#
#      ansible.builtin.shell: curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
#
#- name: remove existing content
#  hosts: localhost
#  tasks:
#    - name: remove file
#      ansible.builtin.file:
#        path: /usr/share/nginx/html
#        state: absent
#
#- name: Unarchive a file that is already
#  hosts: localhost
#  tasks:
#    - name: unarchieve file
#      ansible.builtin.unarchive:
#        src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
#        dest: "/tmp"
#        remote_src: yes
#
#- name: copy to roboshop configuration
#  hosts: localhost
#  tasks:
#    - name: copy roboshop content
#      ansible.builtin.copy:
#        src: /tmp/frontend-main/localhost.conf
#        dest: /etc/nginx/default.d/roboshop.conf
#        remote_src: yes
