- name: Download mongo repo file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: restart mongodb
  ansible.builtin.systemd:
    state: started
    enabled: true

- name: Replace listen IP
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

