- name: Add the Roboshop application user
  when: APP_USER is defined
  ansible.builtin.user:
    name: "{{ APP_USER }}"

- name: Remove previous file
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent

- name: download and extract app content
  ansible.builtin.unarchive:
    src: https://github.com/Aleem410/{{ COMPONENT }}/archive/refs/heads/main.zip
    dest: "/tmp"
    remote_src: yes

- name: copy extracted content to app location
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main/
    dest: "{{ APP_LOC }}"
    remote_src: yes

