- name: rpm nodesource
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: include download app content role
  ansible.builtin.include_role:
    name: common
    tasks_from: download.yml


- name: Install npm package.
  community.general.npm:
    path: "{{ APP_LOC }}"

- name: restart catalogue service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd.yml

