- name: systemd service
  ansible.builtin.template:
    src: templates/systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service


- name: Restart {{ COMPONENT }} service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    state: restarted
    enabled: true
    daemon-reload: true

