- name: systemd service
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service


- name: Restart {{ COMPONENT }} service
  ansible.builtin.systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: "{{ COMPONENT }}"
