name: My First Workflow
on:
  push:
  workflow_dispatch:

jobs:
  First-Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List the files
        run: |
          ls -l
          pwd